import React from 'react';
import {SIGNS} from './western-astrology';
import {SEFIROT} from './kabbalah';
import './personal-methods.css';
const degrees=p=>`${Math.floor(p.degree)}° ${Math.floor((p.degree%1)*60)}′`;
const dot=(angle,r)=>[180+r*Math.cos(angle*Math.PI/180),180-r*Math.sin(angle*Math.PI/180)];
export function AstrologyPanel({chart}){
 if(chart.error)return <p role="status">{chart.error}</p>;
 return <section className="personal-method"><h3>Tu carta natal y el cielo del día</h3><p>{chart.text}</p><p className="method-note">{chart.note} Interpretación simbólica. Orbes: 6° natales y 2° para tránsitos.</p>
 <svg className="natal-wheel" viewBox="0 0 360 360" role="img" aria-label="Carta tropical: posiciones natales, orientación fija con Aries a la derecha. Los datos completos aparecen debajo."><circle cx="180" cy="180" r="168"/><circle cx="180" cy="180" r="125"/>{SIGNS.map((s,i)=>{const [x,y]=dot(i*30,125),[x2,y2]=dot(i*30,168),[tx,ty]=dot(i*30+15,148);return <g key={s}><path d={`M${x} ${y}L${x2} ${y2}`}/><text x={tx} y={ty}>{s.slice(0,3)}</text></g>;})}{chart.natal.filter(p=>chart.birthTimeKnown||p.name!=='Luna').map((p,i)=>{const [x,y]=dot(p.longitude,100-(i%3)*16);return <g key={p.name}><circle cx={x} cy={y} r="3"/><text x={x} y={y-7}>{p.name}</text></g>;})}</svg>
 <details><summary>Posiciones, casas y aspectos de nacimiento</summary><div className="method-table"><table><thead><tr><th>Planeta</th><th>Signo natal</th><th>Grados</th><th>Casa</th></tr></thead><tbody>{chart.natal.filter(p=>chart.birthTimeKnown||p.name!=='Luna').map(p=><tr key={p.name}><td>{p.name}</td><td>{p.sign}</td><td>{degrees(p)}</td><td>{p.house||'Sin confirmar'}</td></tr>)}</tbody></table></div>{chart.ascendant && <p>Ascendente: {chart.ascendant.sign} {degrees(chart.ascendant)}.</p>}{chart.houses.length>0 && <p>Casas por signos enteros: {chart.houses.map(h=>`${h.house}: ${h.sign}`).join(' · ')}</p>}<ul>{chart.natalAspects.map((a,i)=><li key={i}>{a.from} — {a.aspect} — {a.to}: orbe {a.orb}°.</li>)}</ul></details>
 <details open><summary>Tránsitos del momento elegido</summary><p>Relacionan un planeta del momento con uno natal. Se muestran hasta ocho aspectos, ordenados por cercanía angular.</p>{chart.transits.length?<ul>{chart.transits.map((a,i)=><li key={i}>{a.from} actual — {a.aspect} — {a.to} natal: {a.theme} (orbe {a.orb}°).</li>)}</ul>:<p>No hay aspectos dentro del orbe elegido.</p>}<details><summary>Ver las posiciones actuales</summary><p>{chart.current.map(p=>`${p.name}: ${p.sign} ${degrees(p)}`).join(' · ')}</p></details></details>
 <a href="https://www.astro.com/astrology/in_house1_e.htm" target="_blank" rel="noreferrer">Sobre los sistemas de casas</a></section>;
}
const POINTS=[[180,30],[270,90],[90,90],[270,170],[90,170],[180,210],[270,280],[90,280],[180,320],[180,390]];
const EDGES=[[0,1],[0,2],[1,2],[1,3],[2,4],[3,4],[3,5],[4,5],[5,6],[5,7],[6,7],[6,8],[7,8],[8,9]];
export function KabbalahPanel({focus}){
 return <section className="personal-method"><h3>Árbol de la Vida · {focus.name}</h3><p><strong>{focus.quality}:</strong> {focus.text}</p><svg className="life-tree" viewBox="0 0 360 430" role="img" aria-label={`Esquema de las diez sefirot. Cualidad de hoy: ${focus.name}, ${focus.quality}. Líneas esquemáticas, no mapa tradicional de senderos.`}>{EDGES.map(([a,b],i)=><path key={i} d={`M${POINTS[a][0]} ${POINTS[a][1]}L${POINTS[b][0]} ${POINTS[b][1]}`}/>)}{SEFIROT.map((s,i)=><g key={s.name} className={i===focus.index?'selected':''}><circle cx={POINTS[i][0]} cy={POINTS[i][1]} r="28"/><text x={POINTS[i][0]} y={POINTS[i][1]-2}>{s.name}</text><text x={POINTS[i][0]} y={POINTS[i][1]+13} className="tree-quality">{s.quality}</text></g>)}</svg><p><strong>Para practicar:</strong> {focus.action}</p><blockquote>{focus.phrase}</blockquote><p className="method-note">Inspirado en las diez sefirot de la tradición mística judía. Las cualidades y los ejercicios son una adaptación para esta aplicación. {focus.method} El dibujo es un esquema de las cualidades, sin correspondencias astrológicas ni senderos tradicionales.</p><details><summary>Conocer las diez cualidades</summary>{SEFIROT.map(s=><p key={s.name}><strong>{s.name} · {s.quality}:</strong> {s.text}</p>)}</details><a href="https://www.myjewishlearning.com/article/sefirot/" target="_blank" rel="noreferrer">Conocer la tradición de las sefirot</a></section>;
}
